### PR TITLE
Add OOM testing for release process

### PR DESCRIPTION
**Pull request by piotrmiskiewicz**
**Description**

Changes proposed in this pull request:
 - add testing lots of secrets and config maps to the stress test process in the release pipeline

**Related issue(s)**

### CODE REVIEW

**Comment by piotrmiskiewicz** [comment]
running stress test sfor 0.4.5: https://github.com/piotrmiskiewicz/btp-manager/actions/runs/5750183882

**Comment by piotrmiskiewicz** [comment]
stress tests for 0.4.7

**Review by szwedm — APPROVED** [review]
/lgtm

**Pull request merged**
