### PR TITLE
Change OlderCRExists state from error to warning

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

Changes proposed in this pull request:

- Change `OlderCRExists` state from error to warning
- Adjust tests
- Update docs
- Add info on how to fix this warning state

**Related issue(s)**

### CODE REVIEW

**Review by IwonaLanger — APPROVED** [review]

**Review by szwedm — APPROVED** [review]
/lgtm

**Review by IwonaLanger — APPROVED** [review]

**Pull request merged**
