### PR TITLE
Remove 'v' prefix from module-tag in workflows

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

The prefix 'v' was removed from module name

Changes proposed in this pull request:

- Remove 'v' prefix from module-tag in promotion workflow
- Remove 'v' prefix from module-tag in release workflow

**Related issue(s)**

### CODE REVIEW

**Comment by PK85** [comment]
reafactor more: https://github.com/search?q=repo%3Akyma-project%2Fbtp-manager%20v%24&type=code

**Comment by MarekMichali** [comment]
Done

**Review by PK85 — APPROVED** [review]

**Pull request merged**
