### PR TITLE
Simple Create Service Binding Form

### PR DESCRIPTION
**Pull request by ralikio**
**Description**

The following PR contains a simple component for binding creation with a minimal set of fields that allow for binding creation.

Changes proposed in this pull request:

- new `ui/src/components/ServiceBindingForm.tsx` component,
- removed plural from `ServiceInstanceBindings` interface.

**Related issue(s)**

### CODE REVIEW

**Review by szwedm — APPROVED** [review]
/lgtm

**Review by szwedm — APPROVED** [review]
/lgtm

**Comment by ralikio** [comment]
Duplicate

**Pull request closed without merging**
